#!/bin/bash

usage(){
	echo "Usage: AWSPROFILE=profile ${0} <package|deploy|update|delete|validate|run|local>"
	exit 1
}

has(){
	type ${1} >/dev/null 2>&1 || { echo "Command not found: ${1}" 1>&2; exit 1; }
}

package(){
	make build

	# There's a bug in the `cloudformation package` command where
	# execution of a Go binary fails with the following error message:
	#     "errorMessage": "fork/exec /var/task/main: permission denied"
	# 
	# ${AWS} cloudformation package \
	# 	--s3-bucket "${BUCKET}" \
	# 	--s3-prefix "${NAME}" \
	# 	--template-file ${TEMPLATE} \
	# 	--output-template-file cf_package.yml

	local BUCKET="$(cat ${TEMPLATE} | grep S3Bucket | sed -e 's/^.*S3Bucket: //')"
	[ -z "${BUCKET}" ] && abort "BUCKET is empty"
	${AWS} s3 cp main.zip s3://${BUCKET}/${NAME}/main.zip
}

deploy(){
	package
	${AWS} cloudformation deploy \
		--template-file ${TEMPLATE} \
		--stack-name "${NAME}" \
		--capabilities CAPABILITY_NAMED_IAM
}

update(){
	# ${AWS} cloudformation update-stack \
	# 	--stack-name "${NAME}" \
	# 	--template-body file://${TEMPLATE} \
	# 	--capabilities CAPABILITY_NAMED_IAM

	# In most cases, `deploy` is better:
	# https://qiita.com/yasuhiroki/items/8463eed1c78123313a6f

	${AWS} cloudformation deploy \
		--template-file ${TEMPLATE} \
		--stack-name "${NAME}" \
		--capabilities CAPABILITY_NAMED_IAM
}

delete(){
	${AWS} cloudformation delete-stack \
		--stack-name "${NAME}"
	echo "Delete requested."
}

validate(){
	${AWS} cloudformation validate-template \
		--template-body file://${TEMPLATE}
}

run(){
	${AWS} lambda invoke \
		--function-name "mention-notifier" \
		lambda.log
}

main(){
	has aws
	[ -z "${AWSPROFILE}" ] && usage

    NAME="mention-notifier"
    AWS="aws --profile ${AWSPROFILE}"
	TEMPLATE="cf.yml"

	[ -f ${FILE} ] || abord "${FILE} not found."

	HANDLER="${1}"
	shift

	case ${HANDLER} in
		"package")
			package
		;;
		"deploy")
			deploy
		;;
		"update")
			update
		;;
		"delete")
			delete
		;;
		"validate")
			validate
		;;
		"run")
			run
		;;
		*)
			usage
		;;
	esac
}

main $@
