#!/bin/bash


FILE="cf.yml"

[ -f ${FILE} ] || { echo "${FILE} not found."; exit 1; }

repl(){
    echo $(cat ${FILE} | grep ${1} | sed -e "s/^.*${1}: //")
}

cat <<EOL > template.yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MentionNotifier

Resources:
  MentionNotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: ./main.zip
      Environment:
        Variables:
          LOGIN: $(repl LOGIN)
          GITHUB_TOKEN: $(repl GITHUB_TOKEN)
          SLACK_ENDPOINT: $(repl SLACK_ENDPOINT)
          GITHUB_ENDPOINT: $(repl GITHUB_ENDPOINT)
          REASON: $(repl REASON)
          POLLING: $(repl POLLING)
EOL


echo "" | aws-sam-local local \
    invoke MentionNotifierFunction \
    --log-file local.log

rm template.yml
